# Tabular data and Pandas 

## Tabular data

In many machine learning applications, the data is *tabular*, i.e. it can be arranged in rows and columns. 

Each column in the table represents one different *attribute* or *feature* being measured, whilst each row represents an individual *record* (a combination of attribute values that has been observed). 

For example, consider the following table of data containing module marks for five students:

| Student_ID | COM745 | COM761 | COM747 |
| :- | :-: | :-: | :-: |
|12340|64|75|80|
|12344|56|25|40|
|12363|70|62|58|
|12375|66|57|54|
|12383|49|50|65|

In this table:
- each column represents a particular *attribute* (Student_Id, and marks for three modules) of a student 
- each row represents a *record* of attribute values corresponding to a particular student


#### Creating a NumPy array directly
We can create a NumPy array to store these records directly as follows:

In [1]:
import numpy as np

# Create a NumPy array to store the data
marks_array = np.array([[12340,64,75,80],[12344,56,25,40], [12363,70,62,58], [12375,66,57,54], [12383,49,50,65]])
print(marks_array)

[[12340    64    75    80]
 [12344    56    25    40]
 [12363    70    62    58]
 [12375    66    57    54]
 [12383    49    50    65]]



#### Reading numerical data from file using `loadtxt`

It is more common for us to read our data in from files however.

Have a look at `marks.csv` which contains this data in csv (comma separated variable) format. 

In the cell below, we read the data from this file into NumPy arrays using the NumPy `loadtxt` function.

Note the parameters we set in the `loadtxt` function [1]:
- `delimiter =','` because we are reading a csv file.
    - the default value is `None`, which is whitespace.
- `skiprows =1` because the first line in `marks.csv` contains the attribute names. We do not want to store these in our array, so we skip the first line in the file.
    - the default value is 0.
- `dtype=np.int32` means the data we are reading in from file should be stored as integers in the NumPy array.
    - the default value is float64
    - the numerical data types allowed in a NumPy array are given in [2]
    
[1] https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html 

[2] https://numpy.org/devdocs/user/basics.types.html

In [2]:
marks_array_from_file = np.loadtxt('marks.csv', delimiter = ',', skiprows=1,dtype=np.int32)
print(marks_array_from_file)

[[12340    64    75    80]
 [12344    56    25    40]
 [12363    70    62    58]
 [12375    66    57    54]
 [12383    49    50    65]]


In [3]:
print('type of data in marks_array:',marks_array.dtype)
print('type of data in marks_array_from_file:',marks_array_from_file.dtype)

type of data in marks_array: int32
type of data in marks_array_from_file: int32


#### Limitations of `loadtxt`

The `loadtxt` method from NumPy is useful for quickly loading in numerical data from a file into a NumPy array.

However it cannot be used if:
1. the data contains a mixture of different data types, e.g. numerical and string
2. there are missing values in the data

## Tabular data with mixed data types

In many machine learning  problems, some of the attributes are not numerical.

For example, consider the following table containing data about five students:

| Student_ID | Name | Course | Attendance | 
| :- | :- | :-: | :-: |
| 12340 | Ari King | AI | 87 | 
| 12344 | Eugenia Dooley | AI | 45 |
| 12348 | David Raynor | IoT | 52 | 
| 12350 | Chaim Upton | IoT | 51 | 
| 12363 | Mateo Mohr | AI | 90 |


For example, the `Course` attribute is categorical (AI/IoT).

We can still store the above data in a NumPy array using:

In [4]:
# Create a NumPy array; place attribute values that are strings inside quotes
student_array = np.array([[12340,'Ari King','AI',87], [12344,'Eugenia Dooley','AI',45], [12348,'David Raynor','IoT',52], [12350,'Chaim Upton','IoT',51], [12363,'Mateo Mohr','AI',90]])
print(student_array)

[['12340' 'Ari King' 'AI' '87']
 ['12344' 'Eugenia Dooley' 'AI' '45']
 ['12348' 'David Raynor' 'IoT' '52']
 ['12350' 'Chaim Upton' 'IoT' '51']
 ['12363' 'Mateo Mohr' 'AI' '90']]


When printing out `student_array`, notice how there are quotes around every value in the array.
- This indicates each element is some sort of string data structure (even those we would like to be numbers)

In [5]:
print(student_array.dtype)

<U14


Note that `<U14` means:
- < means 'Little Endian' (*don't worry if you don't know what this means*)
- U means 'Unicode'
- 14 means '14 characters'

As before, we can read the data from file using `loadtxt`. 

Note that we have explicitly set `dtype='<U14'` here. The default value for this is float, and so would cause an error if we did not change it to some type of string.

In [6]:
student_array_from_file = np.loadtxt('students.csv', delimiter = ',', skiprows=1,dtype='<U14')
print(student_array_from_file)

[['12340' 'Ari King' 'AI' '87']
 ['12344' 'Eugenia Dooley' 'AI' '45']
 ['12348' 'David Raynor' 'IoT' '52']
 ['12350' 'Chaim Upton' 'IoT' '51']
 ['12363' 'Mateo Mohr' 'AI' '90']]


In [7]:
print(student_array_from_file.dtype)

<U14


## The pandas `DataFrame`

In Python, the `pandas` library offers many useful methods for exploring, cleaning and manipulating tabular data, via an object called a `DataFrame`.

It is much more flexible than NumPy arrays, e.g.: it allows us to deal with categorical data and missing values.

### Creating a pandas DataFrame

Below we show how to create a DataFrame in two ways:
1. Directly from a NumPy array
2. Reading data from a file

#### Creating a pandas DataFrame from a NumPy array
We can create a DataFrame from numpy arrays directly as follows:

In [8]:
import pandas as pd

# Create a Python list that holds the names of the columns (i.e. the names of the attributes).
column_names = ['Student_ID','Student_Name','Course','Attendance']

# Create the DataFrame, using the NumPy array student_array that we created above
student_df_np = pd.DataFrame(data=student_array, columns=column_names)

# Print the DataFrame
student_df_np

Student_ID    Student_Name Course Attendance
0      12340        Ari King     AI         87
1      12344  Eugenia Dooley     AI         45
2      12348    David Raynor    IoT         52
3      12350     Chaim Upton    IoT         51
4      12363      Mateo Mohr     AI         90

#### Creating a pandas DataFrame from a csv file

It is much more common however to create a pandas DataFrame from data stored in files.

The files `marks.csv` and `students.csv` contains the data used above. 

We will create a DataFrame from `students.csv` first:

![csv_to_df](Images/csv_to_df6.png)

In [9]:
students_df = pd.read_csv('students.csv')
students_df

Student_ID    Student_Name Course  Attendance
0       12340        Ari King     AI          87
1       12344  Eugenia Dooley     AI          45
2       12348    David Raynor    IoT          52
3       12350     Chaim Upton    IoT          51
4       12363      Mateo Mohr     AI          90

##### Other `read` methods in pandas

Note, there are many other `read` methods available in pandas, e.g.:
- `read_excel()` for reading in Excel spreadsheets
- `read_json()` for reading JSON files

Consult the documentation for the full list: https://pandas.pydata.org/pandas-docs/stable/reference/io.html

### The axes of the DataFrame

Two axes are used to refer to the two dimensions of a DataFrame:
- Axis 0 spans the rows.
- Axis 1 spans the columns.

An **index** is created along Axis 0, that enables us to refer to individual rows via the `loc` method:

In [10]:
students_df.loc[1]

Student_ID               12344
Student_Name    Eugenia Dooley
Course                      AI
Attendance                  45
Name: 1, dtype: object

The indices for Axis 1 are the attribute names (column headers). We can use these to refer to a specific column:

In [11]:
students_df['Student_Name']

0          Ari King
1    Eugenia Dooley
2      David Raynor
3       Chaim Upton
4        Mateo Mohr
Name: Student_Name, dtype: object

We can specify values for both axes to refer to a specific cell:

In [12]:
students_df.loc[1,'Student_Name']

'Eugenia Dooley'

### Combining DataFrames

Sometimes our data is not in a single file, but instead spread over multiple files.

In these cases we usually:
1. construct a separate DataFrame for each data file.
2. combine the DataFrames.

There are multiple ways to combine two DataFrames.  

#### Combining two DataFrames whose attributes match exactly

First, we deal with cases where the attributes in two files are exactly the same.

First, read the file `students2.csv` to create another DataFrame:

In [13]:
students2_df = pd.read_csv('students2.csv')
students2_df

Student_ID   Student_Name Course  Attendance
0       12340       Ari King     AI          87
1       12348   David Raynor    IoT          52
2       12570  Howard Wunsch     AI          35
3       12572      Elva Feil    IoT         100

As we can see, it has the exact same attributes as our existing DataFrame `students_df`

We can combine these two DataFrames in two ways:
1. Create a new DataFrame containing only records that are in the *intersection* of  `students_df` and `students2_df`
  - i.e. in both `students_df` and `students2_df`
2. Create a new DataFrame containnig records that are in the *union* of `students_df` and `students2_df` 
  - i.e. in `students_df` or `students2_df` (or both)

![merge](Images/merge1.png)

In [14]:
pd.merge(students_df,students2_df)

Student_ID  Student_Name Course  Attendance
0       12340      Ari King     AI          87
1       12348  David Raynor    IoT          52

In [15]:
pd.merge(students_df,students2_df,how='outer')

Student_ID    Student_Name Course  Attendance
0       12340        Ari King     AI          87
1       12344  Eugenia Dooley     AI          45
2       12348    David Raynor    IoT          52
3       12350     Chaim Upton    IoT          51
4       12363      Mateo Mohr     AI          90
5       12570   Howard Wunsch     AI          35
6       12572       Elva Feil    IoT         100

#### Combining DataFrames whose attributes partially match

In [16]:
students_marks_df = pd.read_csv('marks.csv')
students_marks_df

Student_ID  COM745  COM761  COM747
0       12340      64      75      80
1       12344      56      25      40
2       12363      70      62      58
3       12375      66      57      54
4       12383      49      50      65

![MLR51](Images/students_and_marks.png)

##### Left join

- Starting with the left DataFrame, we add columns to represent the additional attributes in the right DataFrame.
  - In this case the left DataFrame is `students_df` and the right DataFrame is `marks_df`
  - We add columns to `students_df` for the attributes COM745, COM761 and COM747.
- At least one attribute is chosen that the two DataFrames share in common, to match rows in the left DataFrame with rows in the right DataFrame.
  - In this case, the only attribute the two DataFrames share in common is `Student_ID`, so we choose it.
- Values for the additional attributes are filled in (where possible) using the right DataFrame. Where this is not possible, a cell is filled with NaN (not a number).
  - For example, consider the first row of `students_df`, which has `Student_ID = 12340`. We can fill out values for COM745, COM761 and COM747 using the first row in `marks_df`, which also has `Student_ID = 12340`.
  - Consider the third row of `students_df`. This has `Student_ID = 12348`. In this case, there is no matching row in `marks_df`, and so COM745, COM761 and COM747 take values of `NaN`.
  
![MLR51](Images/left_merge.png)  

In [17]:
students_df_leftjoin = pd.merge(students_df, students_marks_df, how='left', on='Student_ID')
students_df_leftjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI          87    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI          45    56.0    25.0    40.0
2       12348    David Raynor    IoT          52     NaN     NaN     NaN
3       12350     Chaim Upton    IoT          51     NaN     NaN     NaN
4       12363      Mateo Mohr     AI          90    70.0    62.0    58.0

##### Right join

This is similar to left join, except we start with the right DataFrame and fill missing attribute values using the left DataFrame.

![MLR51](Images/right_merge.png)

In [18]:
student_df_rightjoin = pd.merge(students_df, students_marks_df, how='right', on='Student_ID')
student_df_rightjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI        87.0      64      75      80
1       12344  Eugenia Dooley     AI        45.0      56      25      40
2       12363      Mateo Mohr     AI        90.0      70      62      58
3       12375             NaN    NaN         NaN      66      57      54
4       12383             NaN    NaN         NaN      49      50      65

##### Inner join

Merging this way retain only the rows for which we have values for all attributes across both DataFrames.

![MLR51](Images/inner_join.png)

In [19]:
student_df_innerjoin = pd.merge(students_df, students_marks_df, how='inner', on='Student_ID')
student_df_innerjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI          87      64      75      80
1       12344  Eugenia Dooley     AI          45      56      25      40
2       12363      Mateo Mohr     AI          90      70      62      58

##### Outer join

Merging this way we retain all rows across both DataFrames, filling out attribute values where possible, otherwise filling in NaN.

![MLR51](Images/outer_join.png)

In [20]:
student_df_outerjoin = pd.merge(students_df, students_marks_df, how='outer', on='Student_ID')
student_df_outerjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
5       12375             NaN    NaN         NaN    66.0    57.0    54.0
6       12383             NaN    NaN         NaN    49.0    50.0    65.0

### Useful DataFrame methods

In this section we'll use the `student_df_outerjoin` DataFrame to illustrate some useful methods.

#### Have a quick look at the data
One of the first things we may want to do with data we have loaded into a DataFrame is take a look at the first few rows, to see if it looks how we expect. We can do this using the `head()` method:

In [21]:
# The number we pass indicates how many rows we wish to look at (from the top of the DataFrame)
student_df_outerjoin.head(2)

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0

Or we can look at the final few records instead, using the `tail()` method:

In [22]:
# The number we pass indicates how many rows we wish to look at (from the bottom of the DataFrame)
student_df_outerjoin.tail(1)

Student_ID Student_Name Course  Attendance  COM745  COM761  COM747
6       12383          NaN    NaN         NaN    49.0    50.0    65.0

#### See summaries of the data

The `info()` method provides information about each attribute's data-type and number of non-null values:

In [23]:
student_df_outerjoin.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Student_ID    7 non-null      int64  
 1   Student_Name  5 non-null      object 
 2   Course        5 non-null      object 
 3   Attendance    5 non-null      float64
 4   COM745        5 non-null      float64
 5   COM761        5 non-null      float64
 6   COM747        5 non-null      float64
dtypes: float64(4), int64(1), object(2)
memory usage: 448.0+ bytes


We can see important statistics for the columns that contain numerical data using the `describe()` method:

In [24]:
student_df_outerjoin.describe()

Student_ID  Attendance    COM745     COM761     COM747
count      7.000000    5.000000   5.00000   5.000000   5.000000
mean   12357.571429   65.000000  61.00000  53.800000  59.400000
std       16.440368   21.644861   8.42615  18.512158  14.690133
min    12340.000000   45.000000  49.00000  25.000000  40.000000
25%    12346.000000   51.000000  56.00000  50.000000  54.000000
50%    12350.000000   52.000000  64.00000  57.000000  58.000000
75%    12369.000000   87.000000  66.00000  62.000000  65.000000
max    12383.000000   90.000000  70.00000  75.000000  80.000000

For columns that contain categorical data, we can use:

In [25]:
student_df_outerjoin['Course'].value_counts()

AI     3
IoT    2
Name: Course, dtype: int64

The Pandas DataFrame has many useful functions

In [26]:
student_df_outerjoin.sort_values('Attendance') #Note: INDICES move too (i.e. the index stays with its original row)

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
5       12375             NaN    NaN         NaN    66.0    57.0    54.0
6       12383             NaN    NaN         NaN    49.0    50.0    65.0

In [27]:
print(student_df_outerjoin.head(5)) #Note: DataFrame did not change - thsi is because we need to set inplace=True
#inplace=True means the sort_values sorts the dataframe we are operating on, i.e. student_df_outerjoin;
#onplace=False means the sort_values method returns a new DataFrame, with the values sorted

   Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0


In [30]:
student_df_outerjoin.sort_values('Attendance',ascending=False,inplace=True) #sort by attendance in descending order

In [31]:
print(student_df_outerjoin.head(5))

   Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0


Check out the remainder of the code below in your own time, checking the pandas documentation for more information on what the methods do.

In [32]:
student_df_outerjoin[['Course','Student_ID']]

Course  Student_ID
4     AI       12363
0     AI       12340
2    IoT       12348
3    IoT       12350
1     AI       12344
5    NaN       12375
6    NaN       12383

In [33]:
student_df_outerjoin[student_df_outerjoin['Attendance'] < 50]

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0

In [34]:
student_df_outerjoin[student_df_outerjoin['Course'] == 'AI']

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0

In [35]:
student_df_outerjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
5       12375             NaN    NaN         NaN    66.0    57.0    54.0
6       12383             NaN    NaN         NaN    49.0    50.0    65.0

In [36]:
student_df_outerjoin.iloc[1:3] #Note: indices 1:3 refer to row number, NOT index

Student_ID  Student_Name Course  Attendance  COM745  COM761  COM747
0       12340      Ari King     AI        87.0    64.0    75.0    80.0
2       12348  David Raynor    IoT        52.0     NaN     NaN     NaN

In [37]:
student_df_outerjoin.nlargest(2, 'Attendance')

Student_ID Student_Name Course  Attendance  COM745  COM761  COM747
4       12363   Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340     Ari King     AI        87.0    64.0    75.0    80.0

In [38]:
student_df_outerjoin.nsmallest(3, 'Attendance')

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN

In [39]:
student_df_outerjoin

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
2       12348    David Raynor    IoT        52.0     NaN     NaN     NaN
3       12350     Chaim Upton    IoT        51.0     NaN     NaN     NaN
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
5       12375             NaN    NaN         NaN    66.0    57.0    54.0
6       12383             NaN    NaN         NaN    49.0    50.0    65.0

In [40]:
#Sum values of each object
student_df_outerjoin.sum()

Student_ID    86503.0
Attendance      325.0
COM745          305.0
COM761          269.0
COM747          297.0
dtype: float64

In [41]:
# Count non-NA/null values of each object.
student_df_outerjoin.count()

Student_ID      7
Student_Name    5
Course          5
Attendance      5
COM745          5
COM761          5
COM747          5
dtype: int64

In [42]:
student_df_outerjoin.median()

Student_ID    12350.0
Attendance       52.0
COM745           64.0
COM761           57.0
COM747           58.0
dtype: float64

In [43]:
student_df_outerjoin.var()

Student_ID    270.285714
Attendance    468.500000
COM745         71.000000
COM761        342.700000
COM747        215.800000
dtype: float64

In [44]:
student_df_outerjoin.std()

Student_ID    16.440368
Attendance    21.644861
COM745         8.426150
COM761        18.512158
COM747        14.690133
dtype: float64

In [45]:
student_df_outerjoin.quantile([0.25,0.75])

Student_ID  Attendance  COM745  COM761  COM747
0.25     12346.0        51.0    56.0    50.0    54.0
0.75     12369.0        87.0    66.0    62.0    65.0

also check out min(), max(), mean(), std(), var()

In [46]:
student_df_outerjoin.dropna()

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0

In [47]:
student_df_outerjoin.fillna(0)

Student_ID    Student_Name Course  Attendance  COM745  COM761  COM747
4       12363      Mateo Mohr     AI        90.0    70.0    62.0    58.0
0       12340        Ari King     AI        87.0    64.0    75.0    80.0
2       12348    David Raynor    IoT        52.0     0.0     0.0     0.0
3       12350     Chaim Upton    IoT        51.0     0.0     0.0     0.0
1       12344  Eugenia Dooley     AI        45.0    56.0    25.0    40.0
5       12375               0      0         0.0    66.0    57.0    54.0
6       12383               0      0         0.0    49.0    50.0    65.0

In [48]:
students_df.groupby('Course').mean()

Student_ID  Attendance
Course                        
AI         12349.0        74.0
IoT        12349.0        51.5