<a href="https://colab.research.google.com/github/ofithcheallaigh/uu_pgc_ai/blob/main/Machine%20Learning/Week1/Completed%20Exercises/Exercise_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Exercises

## Exercise 1

Let 

$A = \begin{bmatrix} 1 & 4 \\ 3 & -1 \\ 0 & 7 \end{bmatrix}, B = \begin{bmatrix} 2 & 1 & 3 \\ -5 & 6 & 1 \end{bmatrix}, C = \begin{bmatrix} -3 \\ 9 \\ 0 \\ 9 \end{bmatrix}, D = \begin{bmatrix} 2 & 1 \\ -3 & 0 \end{bmatrix}$

(a) Represent each matrix in Python and determine its order.

(b) Display the transpose of each matrix.

(c) What is $A + B^T$?

(d) What is $D^T - 2D$?

Below are the answer for Exercise 1(a)

In [1]:
import numpy as np

# Matrix A
A = np.matrix('1 4; 3 -1; 0 7')
print("Matrix A is:\n",A)
print("and its order is:", A.shape)

# Matrix B
B = np.matrix('2 1 3; -5 6 1')
print("\nMatrix B is:\n",B)
print("and its order is:", B.shape)

# Matric C
C = np.matrix('-3;9;0;9')
print("\nMatrix C is:\n",C)
print("and its order is:", C.shape)

# Matrix D
D = np.matrix('2 1; -3 0')
print("\nMatrix D is:\n",D)
print("and its order is:", D.shape)

Matrix A is:
 [[ 1  4]
 [ 3 -1]
 [ 0  7]]
and its order is: (3, 2)

Matrix B is:
 [[ 2  1  3]
 [-5  6  1]]
and its order is: (2, 3)

Matrix C is:
 [[-3]
 [ 9]
 [ 0]
 [ 9]]
and its order is: (4, 1)

Matrix D is:
 [[ 2  1]
 [-3  0]]
and its order is: (2, 2)


Below are the answer for Exercise 1(b)

In [2]:
# Transposing the matrices
print("The transpose of matrix A is:\n",A.T)
print('\n')                                           # This is just to make it look better when printing
print("The transpose of matrix B is:\n",B.T)
print('\n')
print("The transpose of matrix C is:\n",C.T)
print('\n')
print("The transpose of matrix D is:\n",D.T)

The transpose of matrix A is:
 [[ 1  3  0]
 [ 4 -1  7]]


The transpose of matrix B is:
 [[ 2 -5]
 [ 1  6]
 [ 3  1]]


The transpose of matrix C is:
 [[-3  9  0  9]]


The transpose of matrix D is:
 [[ 2 -3]
 [ 1  0]]


Below is the answer for Exercise 1(c)

In [3]:
# A + Transpose of B
answer = A + B.T
print("The result of A + B.T is:\n", answer)

The result of A + B.T is:
 [[ 3 -1]
 [ 4  5]
 [ 3  8]]


Below is the answer for Exerice 1(d)

In [4]:
print("The answer for D Transposed, minus 2D is:\n", D.T - 2*D)

The answer for D Transposed, minus 2D is:
 [[-2 -5]
 [ 7  0]]


## Exercise 2
If possible carry out the following matrix multiplications based on the matrices from Exercise 1.

(a) $BD$

(b) $D^TA^T$

(c) $CC^T$

(d) $D^2$, $D^3$, $D^4$, $D^5$

(e) Show that $AB \neq BA$

Below are the answer to Exercise 2(a)

In [5]:
orderB = B.shape
orderD = D.shape

if orderB[1] == orderD[0]:
  print("The multiplication of matrix B and D is:\n", B @ D)
else:
  print("The order of the matrices do not allow multplication")


The order of the matrices do not allow multplication


Below is the answer to Exercise 2(b)

In [6]:
transD = D.T
transA = A.T
orderTransD = transD.shape
orderTransA = transA.shape

if orderTransD[1] == orderTransA[0]:
  print("The multiplication of matrix D transposed and A transposed is:\n", transD @ transA)
else:
  print("The order of the matrices do not allow multplication")

The multiplication of matrix D transposed and A transposed is:
 [[-10   9 -21]
 [  1   3   0]]


Below is the answer to Exercise 2(c)

In [7]:
transC = C.T
orderC = C.shape
orderTransC = transC.shape

if orderC[1] == orderTransC[0]:
  print("The multiplication of matrix C and C transposed is:\n", C @ transC)
else:
  print("The order of the matrices do not allow multplication")

The multiplication of matrix C and C transposed is:
 [[  9 -27   0 -27]
 [-27  81   0  81]
 [  0   0   0   0]
 [-27  81   0  81]]


Below is the answer to Exercise 2(d)

In [12]:
print("D^2 is:\n", np.linalg.matrix_power(D,2))
print("D^3 is:\n", np.linalg.matrix_power(D,3))
print("D^4 is:\n", np.linalg.matrix_power(D,4))
print("D^5 is:\n", np.linalg.matrix_power(D,5))

D^2 is:
 [[ 1  2]
 [-6 -3]]
D^3 is:
 [[-4  1]
 [-3 -6]]
D^4 is:
 [[-11  -4]
 [ 12  -3]]
D^5 is:
 [[-10 -11]
 [ 33  12]]


Below are the answers for Exercise 2(e)

In [23]:
# Show that AB =/= BA
AB = (A @ B)
BA = (B @ A)

print("Matrix AB:\n", AB)
print("Matrix BA:\n", BA)
print("These matricies are shown to be different")


# if(AB.all() == BA.all()):
#   print("I cannot show that they matricies are different")
# else:
#   print("These matricies are shown to be different")

Matrix AB:
 [[-18  25   7]
 [ 11  -3   8]
 [-35  42   7]]
Matrix BA:
 [[  5  28]
 [ 13 -19]]
These matricies are shown to be different


## Exercise 3
Solve the following set of linear equations for $x$, $y$ and $z$:

\begin{align}
x + y + z & = 3 \\
2x  + 7y + 2z & = 15 \\
-3x + 4y + z & = 0
\end{align}

In [25]:
lhs = np.array([[1,1,1,],[2,7,2],[-3,4,1]])
rhs = np.array([[3,15,0]]).T

print("Left hand side of the equation:\n",lhs)
print("Right hand side of the equation:\n",rhs)

result = np.linalg.solve(lhs,rhs)
print("The x, y and z values are:\n",result)

Left hand side of the equation:
 [[ 1  1  1]
 [ 2  7  2]
 [-3  4  1]]
Right hand side of the equation:
 [[ 3]
 [15]
 [ 0]]
The x, y and z values are:
 [[ 2.1]
 [ 1.8]
 [-0.9]]


## Exercise 4

Write a function `euclidean_distance` that returns the Euclidean distance $d$ between two row vectors $\mathbf{x}$ and $\mathbf{y}$.

$d = \sqrt{\sum_{i=1}^{n} (x_i - y_i)^2}$

In [27]:
def euclidean_distance(x,y):
  d = 0
  d = np.sqrt(np.sum((x-y)**2, axis = 1))
  return d 

# Code check
a = np.array([[2,4,5,2]])
b = np.array([[5,3,0,1]])
d = euclidean_distance(a,b)
print(d)

[6.]
